### ISSUE TITLE
Revisão de Registro.

### ISSUE THREAD

**Issue by gtorrezani** [chinnonsantos/sql-paises-estados-cidades#1]
Não estou certo de qual lista foi utilizada para dar a carga nos países, mas para mim o código 6781 de São Cristovão e Neves, Ilhas deu como inválido, o que passou foi o 6955 conforme descrito em http://www.bcb.gov.br/Rex/ftp/paises.asp

**Comment by chinnonsantos** [comment]
Obrigado pela revisão @gtorrezani, estarei verificando se não haverá conflito e atualizo a tabela, se possível mande um Pull Request.
