### ISSUE TITLE
DDI

### ISSUE THREAD

**Issue by renato71amorim** [chinnonsantos/sql-paises-estados-cidades#15]
Primeiro parabéns e muito obrigado pro compartilhar! Se me permite uma sugestão: Que tal incluir o código DDI na tabela países.

**Comment by chinnonsantos** [comment]
Boa sugestão @renato71amorim,

Assim que estiver um tempo, implemento essa melhoria, estou com dados de geolocalização para incluir nos municípios também, aproveito e já faço junto.
