### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by DenisonMartins** [chinnonsantos/sql-paises-estados-cidades#19]
Criar scripts para atender ao SGBD Oracle

**Comment by DenisonMartins** [comment]
Chinnon estou elaborando os scripts para o SGBD Oracle e irei fazer um pull request.

**Comment by chinnonomega** [comment]
Olá @DenisonMartins

Desculpe a demora, obrigado pela contribuição, estarei analisando o PR neste momento.

Sinta-se livre para contribuir com sugestões e código, sempre. Abraços.
