### ISSUE TITLE
Sugestão de Inclusão conforme ISO.

### ISSUE THREAD

**Issue by gtorrezani** [chinnonsantos/sql-paises-estados-cidades#2]
AX - Åland Islands
BL - Saint Barthélemy
CW - Curaçao
JE - Jersey
MF - Saint Martin
SX - Sint Maarten (Dutch part)

**Comment by chinnonsantos** [comment]
@gtorrezani, Ótima sugestão, todas foram incluídas exceto a Jersey (**JE**) que só foi atualizadas a SIGLA do registro 'Bailiwick of Jersey (**Jersey, Ilha do Canal**) - BACEN **1508**'.

Fonte de Pesquisa: 

- _Instruções de Preenchimento do Banco Central - Março de 2016 - [Link](http://www.bcb.gov.br/fis/pstaw10/DLO_2061_e_2071_instrucoesComplementares_ACP_v201603.pdf)_
- _Wikipedia_
