### ISSUE TITLE
Erro de sintaxe ao importar Script das Cidades

### ISSUE THREAD

**Issue by LeandroAlcantara-1997** [chinnonsantos/sql-paises-estados-cidades#23]
Ao importar o script das cidades assim que começa a importar os dados da tabela, ele dá erro de sintaxe no PostgreSQL.

**Comment by luizvaz** [comment]
O meu está correto:
[https://github.com/luizvaz/sql-basic-tables/tree/master/PostgreSQL](https://github.com/luizvaz/sql-basic-tables/tree/master/PostgreSQL)

**Comment by LeandroAlcantara-1997** [comment]
Boa noite.
Muito obrigado.
Hoje irei alterar o script e reenviarei.

Atenciosamente,
Leandro Alcantara.

Em qui, 12 de ago de 2021 23:56, Luiz Vaz ***@***.***>
escreveu:

**Comment by RickLeite** [comment]
_"COPY tbl FROM STDIN"_ não é suportado pelo pgadmin, vc vai ter que importar pelo sql shell

**Comment by RickLeite** [comment]
Resolução: Coloque o arquivo Cidades em seu diretorio raiz. C:\
Abra o cmd e digite "psql -U postgres -d cities < C:\cidade.sql"
O comando é composto de : 
-U (usuario)
-d (database)

Verifique se o PSQL esta alocado nas variaveis de ambiente

**Comment by chinnonsantos** [comment]
Senhores, estarei dando como encerrada essa Issues após o PR #24 do nosso querido @volneineves ter corrigido o uso do scripts para PostgreSQL. Obrigado pelos comentários e sugestões, a contribuição de vocês é muito importante para manter o repositório útil para muitos profissionais da área de tecnologia. Abraços.
