### ISSUE TITLE
Arquivo de cidade incompleto

### ISSUE THREAD

**Issue by leanmarqs** [chinnonsantos/sql-paises-estados-cidades#26]
Notei que a cidade em que vivo não está presente no arquivo de cidade. O nome é Angicos, no Rio Grande do Norte. Link do IBGE https://[cidades.ibge.gov.br/brasil/rn/angicos](https://cidades.ibge.gov.br/brasil/rn/angicos/panorama)/panorama.

**Comment by chinnonsantos** [comment]
Obrigado @leanmarqs , a cidade foi adicionada.
