### ISSUE TITLE
Remoção de registro

### ISSUE THREAD

**Issue by gtorrezani** [chinnonsantos/sql-paises-estados-cidades#4]
Remoção da Yuguslavia

**Comment by chinnonsantos** [comment]
@gtorrezani, não seria interessante manter o registro da Iugoslávia (Yuguslavia em Inglês) para que possa ser feito utilização da base de dados para datações antigas (antes de 1991 quando foi dividida...)??? imaginemos que algum sistema precise registrar locais de nascimento de estrangeiros, e ele tenha nascido na antiga Yuguslavia, o documento de nascimento dele ainda vai esta com o registro antigo.

**Comment by chinnonsantos** [comment]
Foi atualizado os dados da Iugoslávia com base nas informações do Banco Central - [Link](http://www.bcb.gov.br/rex/Censo2000/port/manual/pais.asp?idpai=censo2000inf)
